/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leavemanagementsystempbl;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static leavemanagementsystempbl.LoginForm.userid;

/**
 *
 * @author Pradnesh
 */
public class facultyWindow extends javax.swing.JFrame {


    /**
     * Creates new form facultyWindow
     */
    public facultyWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        el = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Leave Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 580, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Name  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 89, 210, 60));

        user1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 0, 51));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 89, 230, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("CL Remaining :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 160, 210, 60));

        cl.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cl.setForeground(new java.awt.Color(255, 0, 51));
        cl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 160, 100, 60));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("EL Remaining :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 231, 210, 60));

        el.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        el.setForeground(new java.awt.Color(255, 0, 51));
        el.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(el, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 231, 100, 60));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("SL Remaining :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 302, 210, 60));

        sl.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sl.setForeground(new java.awt.Color(255, 0, 51));
        sl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(sl, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 302, 100, 60));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 380));

        jMenu1.setText("Leave Manager");

        jMenuItem3.setText("Apply for leave");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Leave catalog");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Profile");

        jMenuItem1.setText("view profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("log out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        LoginForm lf = new LoginForm();
                lf.setVisible(true);
                lf.pack();
                lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            String usern = null;
            // TODO add your handling code here:
            LAForm laf = new LAForm();
            laf.id.setText(userid.getText());
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/pbl","postgres", "1234");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM PBL_USERS");
            
            while(rs.next())
            {
               if(rs.getString(1).equals(userid.getText()))
               {
                   usern = rs.getString(2);
                   break;
               }
            }
            con.close();
            laf.username.setText(usern);
            laf.setVisible(true);
            laf.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(facultyWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        LCfaculty1 lcf = new LCfaculty1();
        lcf.setVisible(true);
        lcf.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        profile pf = new profile();
        pf.usr.setText(userid.getText());
        pf.setVisible(true);
        pf.setLocationRelativeTo(null);
        this.setVisible(false);
        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/pbl","postgres", "1234");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM PBL_USERS");
            
            while(rs.next())
            {
                if(userid.getText().equals(rs.getString(1)))
                {
                pf.jLabel8.setText(rs.getString(2));
                pf.jLabel9.setText(rs.getString(8));
                pf.jLabel10.setText(rs.getString(9));
                pf.jLabel17.setText(rs.getString(10));
                pf.jLabel12.setText(rs.getString(7));
                pf.jLabel13.setText(rs.getString(6));



                }
            
            }
           
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facultyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facultyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facultyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facultyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facultyWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel cl;
    public static javax.swing.JLabel el;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel sl;
    public static javax.swing.JLabel user1;
    // End of variables declaration//GEN-END:variables
}
