/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leavemanagementsystempbl;

/**
 *
 * @author Pradnesh
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import static leavemanagementsystempbl.LoginForm.userid;
public class LeaveApplications extends javax.swing.JFrame {

    /**
     * Creates new form LeaveApplications
     */
    public LeaveApplications() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jComboBox1 = new javax.swing.JComboBox<>();
        pblPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("pblPU").createEntityManager();
        leaveapplyhodQuery = java.beans.Beans.isDesignTime() ? null : pblPUEntityManager.createQuery("SELECT l FROM Leaveapplyhod l");
        leaveapplyhodList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : leaveapplyhodQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jComboBox1.setMaximumRowCount(2);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accept", "Decline" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(102, 255, 102));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, leaveapplyhodList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${srNo}"));
        columnBinding.setColumnName("Sr.No.");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userid}"));
        columnBinding.setColumnName("User ID");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${username}"));
        columnBinding.setColumnName("Username");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${leaveApplyDate}"));
        columnBinding.setColumnName("Leave Apply Date");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${leaveEndDate}"));
        columnBinding.setColumnName("Leave End Date");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noOfDays}"));
        columnBinding.setColumnName("No Of Days");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${leavetype}"));
        columnBinding.setColumnName("LeaveType");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${leavereason}"));
        columnBinding.setColumnName("LeaveReason");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${leavestatus}"));
        columnBinding.setColumnName("LeaveStatus");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(8).setCellEditor(new DefaultCellEditor(jComboBox1));
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 466, 100, 35));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 466, 100, 35));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 810, 60));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HODForm hf = new HODForm();
                hf.setVisible(true);
                hf.pack();
                hf.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Statement st;
         
        try 
        {
            
           Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/pbl","postgres", "1234");
           int k=10;  
          /* Statement stm = conn.createStatement();
           ResultSet rs = stm.executeQuery("SELECT * FROM PBL_USERS");
           while(rs.next())
            {
            if(rs.getString(2).equals(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),1)))
                {
                    switch((String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(),6))
                        {
                        case "cl": 
                            k=rs.getInt(8);
                        System.out.println("running..");    
                            break;
                        case "el": 
                            k=rs.getInt(9);
                            break;
                        case "sl": 
                            k=rs.getInt(10);
                            break;
                        }
                }
            }*/
           String sql= "update pbl_users set leavetype"+(String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),6)+"='"+(k-(int)(jTable1.getModel().getValueAt(jTable1.getSelectedRow(),5)))+"' where userid='"+jTable1.getModel().getValueAt(jTable1.getSelectedRow(),1)+"'";
           Statement stmt = conn.createStatement();
          
           System.out.println(""+sql);
            String s;
             s = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),8);
             System.out.println(""+s);
            if(s.equals("Accept")) {
                stmt.executeUpdate(sql);
            }
            
        Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/pbl","postgres", "1234");
            PreparedStatement pst = con.prepareStatement("update leaveapplyhod set leavestatus=? where userid=?;");
            pst.setString(1, (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),8));
            pst.setString(2, (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),1));
            pst.executeQuery();
            PreparedStatement pst2 = con.prepareStatement("update leaveapply set leavestatus=? where userid=?;");
            pst2.setString(1, (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),8));
            pst2.setString(2, (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),1));
            pst2.executeQuery();
           st = con.createStatement();
            /*String s;
             s = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),8);
             System.out.println(""+s);
            if(s.equals("Accept")) {
                stmt.executeUpdate(sql);
            }*/             
        con.close();    
        conn.close();    
        }
        catch(SQLException e)
        {
        System.out.println(""+e);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveApplications().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<leavemanagementsystempbl.Leaveapplyhod> leaveapplyhodList;
    private javax.persistence.Query leaveapplyhodQuery;
    private javax.persistence.EntityManager pblPUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
